### PR TITLE
feat: add support for specifying collection names used in transformed URL paths

### LINKED ISSUE #24: feat: support mapping a content collection directory name to a site page path
In a situation where a custom collection in a directory of `src/content/docs` is mapped to something other than the physical content collection directory name, the wrong url is generated.

It is mentioned in the assumptions located at the top of the [README](https://github.com/vernak2539/astro-rehype-relative-markdown-links?tab=readme-ov-file#astro-rehype-relative-markdown-links) that this scenario is not covered, however I think it would be fairly simple to, at a minimum, handle collection name mappings (path -> directory).  Beyond that, for things like handling other path segments, it gets way more complex without internal Astro info and/or metadata in options.

For example, in the following directory structure, the `[...slug].astro` is written to use the content collection `docs` in the directory `docs`, however the path to the page (virtualized essentially) is `my-docs/test` and not `docs/test`.

```text
.
├── src/
│   ├── content/
│   │   ├── docs/
│   │   |   └── test.md
|    ├── pages/
│   │   ├── my-docs/
│   │   |   └── [...slug].astro
```

Repro: <https://stackblitz.com/edit/github-pdzrjo-gg4trc>

Steps to reproduce:

1. Open repro
2. Click on any of the links in the `Collection Root` or `Collection Subdir` sections

Expected Result:
The links generated should be `my-docs/[slug]` and navigate successfully

Actual Result:
The links generated are `docs/[slug]` and 404

3. Go to the `Debug` page
4. Click any of the links and they will all work because they target `my-docs/[slug]`

We do not have internal information so there is no current way to detect this situation.  Ideas on ways to solve for this situation:

1. Add an option `collectionNames` which is a key/value pair that makes a physical directory to the collection name.  For example, using the above:
```js
export default defineConfig({
  markdown: {
    rehypePlugins: [
      [
        rehypeAstroRelativeMarkdownLinks,
        {
          collectionNames: {
            docs: 'my-docs`
          }
        },
      ],
    ],
  },
});
```

2. Leverage metadata in the link in the markdown (similar to the way classes, titles, etc. work)
```markdown
[Some Text](some-url title){ .class-1 }
```

I think Option 1 makes the most sense as Option 2 is highly dependent on markdown processer, is very error prone and would require every link to have the metadata rather than just a single place to do the mapping as would be the case in option 1.

Thoughts?  Other ideas on how to solution and if you think this scenario is worth solving for?

### PR DESCRIPTION
**Pull request by techfg**
**IMPORTANT** - This is based on PR #49 and should only be merged after it assuming you are comfortable with these sets of changes.

Resolves #24

### CODE REVIEW

**Comment by fr3fou** [comment]
Any updates this?

**Comment by vernak2539** [comment]
> Any updates this?

Sorry, this is my bad. I don't have much time these days (and haven't for a while). I'll try to dedicate some time to getting some of these things merged and updated. thanks @techfg for being so active on this!

**Comment by techfg** [comment]
Hi @vernak2539 -

I merged latest from `techfg:fix/remove-contentpath-option` into this PR since this PR is based on #49 to resolve the conflicts and hopefully makes things a bit easier on you assuming you move forward with merging #49 and this PR.  

The merge from `techfg:fix/remove-contentpath-option` into this PR was more straightforward than the merge from `main` to `techfg:fix/remove-contentpath-option` but the same warnings mentioned [here](https://github.com/vernak2539/astro-rehype-relative-markdown-links/pull/49#issuecomment-2495731548) still apply.  In short, I believe I merged properly but given the nature of all the changes across the PRs, there is a chance that I missed something and/or merged incorrectly.  All the tests pass and things should be good but just mentioning this in case any issues crop up (assuming this PR is merged) so we can circle back to the merge in to `techfg:fix/remove-contentpath-option` and this merge as the likely culprit(s).

**Comment by techfg** [comment]
@vernak2539 - No worries, I should be able to get to these today.

**Comment by techfg** [comment]
@vernak2539 - Should be good to go, lemme know if you have any issues, thanks!

**Pull request merged**
