### PR TITLE
feat: Add srcDir & align `collection base` on a per collection basis (remove contentPath + contentPathMode)

### LINKED ISSUE #47: bug: `contentPath` is required in order to correctly transform when `collectionPathMode` is root
When `collectionPathMode='root'`, the [`contentPath`](https://github.com/vernak2539/astro-rehype-relative-markdown-links/blob/main/docs/interfaces/Options.md#contentpath) option must be specified and point to the content collection that should be treated as the `site root` in order to transform a content collection to the site root.  

For example, given the following directory structure & markdown file references:

```text
.
├── src/
│   ├── content/
│   │   ├── blog/
│   │   |   ├── item-1.md/
│   │   |   ├── item-2.md/
│   │   ├── newsletter/
│   │   |   ├── item-1.md/
│   │   |   ├── item-2.md/
```

`src/content/blog/item-1.md`
```markdown
[Blog Item 2](./item-2.md)
```

`src/content/newsletter/item-1.md`
```markdown
[Newsletter Item 2](./item-2.md)
```

In order to have the `blog` content collection treated as `site root`, the following configuration is required:

```js
{  
  collectionPathMode: 'root',
  contentPath: 'src/content/blog'
}
```

Repro: <https://stackblitz.com/edit/withastro-astro-npyzr7>
Steps to reproduce:
1. Navigate to <https://stackblitz.com/edit/withastro-astro-npyzr7>
2. Click on `Blog Item 1` - Results in 404 because the transformed path is `/blog/item-1.md`
3. Add `contentPath: 'src/content/blog'` to the plugin options in [astro.config.mjs](https://stackblitz.com/edit/withastro-astro-npyzr7?file=astro.config.mjs%3AL8)
4. Repeat step 1 & 2

`contentPath` was added in [v0.5.0](https://github.com/vernak2539/astro-rehype-relative-markdown-links/tree/v0.5.0) to support treating a content collection as the site root (see #2) so that the collection name was not prefixed to the transformed path.  However, the `contentPath` option had some shortcomings:

1. It did not handle all situations where the intended outcome was that the collection should be treated as site root (see issue #18 and PR #19).
1. It provided the ability for the user to specify a `content directory` which Astro does not allow, it is always `./content` relative to the [srcDir](https://docs.astro.build/en/reference/configuration-reference/#srcDir) option.  Beyond that, it creates unnecessary confusion because the `contentPath` points to a specific content collection whereas in Astro lingo, the content path should contain subdirectories of content collections.
1. While multiple content collections would still work even with `contentPath` pointing to a specific content collection directory (because of relative paths), the option was applied to all content collections when it was intended to only identify one content collection as the `site root`.

When `collectionPathMode` was added in #19, it resolved the issues in #18, however it did not address the other two issues.  With `collectionPathMode` in-place, there is no need for the `contentPath` to be specified and it should be removed.  In its place, a `srcDir` option should be added to align with Astro's [srcDir](https://docs.astro.build/en/reference/configuration-reference/#srcDir) option.

### PR DESCRIPTION
**Pull request by techfg**
**IMPORTANT** - This PR contains the fixes in #55 so should be merged after it.

❗ **IMPORTANT: Breaking Change**❗ 

If I'm understanding the way [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) works, adding a label named [`Breaking changes:`](https://github.com/github-changelog-generator/github-changelog-generator/blob/7d183b2788d670e2dd9be8cf7db130421f21f1a6/man/git-generate-changelog.md?plain=1#L42) to this PR and/or issue #47 should annotate the generated changelog with the information about the breaking change.  Alternatively, it looks like adding a label [`breaking`](https://github.com/github-changelog-generator/github-changelog-generator/blob/7d183b2788d670e2dd9be8cf7db130421f21f1a6/man/git-generate-changelog.md?plain=1#L150) to issue #47  would do the same thing so either way "should" work.

1. Eliminates `contentPath` option
2. Adds `srcDir` option
3. Eliminates `contentPathMode`
4. Adds `collectionBase` and `collections` options to align the application of collection base on a per collection basis rather than unilaterally to all collections

As detailed in #47, PR #2 had some shortcomings that PR #18 did not fully address.  This PR addresses the remaining issues and creates the options needed to support future flexibility (e.g., #24 & #27).

FYI - I couldn't quite get the docs to emit inline the way I wanted so still working through that part.  I did add a `@see` section and generated a separate interface doc for the new [CollectionConfig](https://github.com/vernak2539/astro-rehype-relative-markdown-links/pull/49/files#diff-711d8e8e29632d7bfa35f2271db0b9c0646e3287fe1695e282d53508bba564c2) options so the docs are covered, just not the way that I would ideally want them to generate.  Might be a limitation with typedoc & zod or (hopefully) just operator error.  I'll keep at it and submit separate PR if you agree with this one and it gets merged beforehand.

Resolves #47

### CODE REVIEW

**Comment by vernak2539** [comment]
I really like this idea, as it does open a lot of possibilities. I'm going to have to take a moment to load all the context back into my mind, so it may take me a few days! (i'm looking though!)

**Comment by techfg** [comment]
Sounds good!  PR #50 which addresses Option 1 from #24 is based on this PR so this one should come first.  Ahead of this one though, would recommend you review 55, 36, 48, 51, 56 & 58 in that order first.  They are all pretty small and built directly on top of main and should simplify merging for this one, 50 and the potentially 52 (review this one last and see all my comments in the PR regarding my current thoughts on it).

**Comment by vernak2539** [comment]
- [x] #55 
- [x] #36 
- [ ] #48 (questions/comments!)
- [ ] #51
- [ ] #56
- [ ] #58

**Comment by techfg** [comment]
Hi @vernak2539 -

I merged latest from `main` into this PR to resolve the conflicts and hopefully makes things a bit easier on you assuming you move forward with merging this PR.  

Note that the merge was not trivial due to the changes in this PR and changes in the other PRs that were merged back in May as well as recently.  I believe I merged properly but given the nature of all the changes across the PRs, there is a chance that I missed something and/or merged incorrectly.  All the tests pass and things should be good but just mentioning this in case any issues crop up (assuming this PR is merged) so we can circle back to this merge as the likely culprit.

**Comment by vernak2539** [comment]
Looks good to me! I've pushed a few changes to the PR (mostly to revert docs changes, which are generated automagically now after merges to main).

I've tested these changes by linking it to my blog, and everything seems great! 

I'll merge #50 soon, then we can get a release out.

**Comment by techfg** [comment]
@vernak2539 - 

Awesome, great to see this merged, thank you and glad to hear that it worked seamlessly with your blog!

Regarding docs, noted on the auto generate, I'll avoid generating on future PRs :)  Also, FYI that I'll be submitting a PR to fix some typing and docs issues once #50 is merged since, as discussed on previous PRs, there are some shortcomings on both :)

**Pull request merged**
