### PR TITLE
fix: handle collections in root of site (#18)

### LINKED ISSUE #18: bug: When `contentPath` is the same as the `collectionPath`, some transformed paths are incorrect
In a situation where the `contentPath` is the same as the `collectionPath`, transformed paths in a few situations do not generate correctly.  While it seems a bit odd to have these be the same, it's actually the way [Starlight](https://starlight.astro.build/) works and [Astro's docs](https://github.com/withastro/docs/blob/main/astro.config.ts#L27) are based on Starlight.  Starlight hoists `src/content/docs` to the [root of the site](https://github.com/withastro/starlight/blob/main/packages/starlight/index.ts#L50) so instead of an expected path of `/docs/subdir/page` you get `/subdir/page`.  In this scenario, the `collectionPath` becomes the same as the `contentPath` from a routing perspective.

> [!NOTE]
> To utilize [astro-rehype-relative-markdown-links](https://github.com/vernak2539/astro-rehype-relative-markdown-links) with Starlight, the plugin configuration must contain `contentPath: 'src/content/docs'` for paths to resolve correctly.  See `Additional Information` below for more details/thoughts.

Regarding the issue that this all presents:

1. References to the `root` index.md transform to empty string (`''`).  For a page in the `docs` folder (the effective root) referencing the "root" index page:
```markdown
Markdown: [home page](./index.md)
Transformed Url: `''`
```

2. Pages with custom slug have their collection paths "double-up". 
- For a page `docs/subdir/mypage.md` with a custom slug of `subdir/my-page`, the following markdown in a page in docs (root) folder:
```markdown
Markdown: [My Page](./subdir/mypage.md)
Transformed Url: `subdir/subdir/my-page)
```
- For a page `docs/myslugpage.md` with a custom slug of `my-slug-page`, the following markdown in a page in docs (root) folder:
```markdown
Markdown: [My Slug Page](./myslugpage.md)
Transformed Url: `myslugpagemd/my-slug-page`
```

Repro:
- <https://stackblitz.com/edit/github-pdzrjo-ygvgvu>

With Proposed Fixes from PR #21:
- <https://stackblitz.com/edit/github-pdzrjo-qnmg8l>

Steps to reproduce:

1. Open repro
    - **NOTE:** The site opens at `/index` because that is the default behavior of Astro for index documents in the site/collection root.  Setting the `slug` to undefined is required for the route to be `/` for root index pages.  The [code in the repro](https://stackblitz.com/edit/github-pdzrjo-ygvgvu?file=src%2Fpages%2F[...slug].astro%3AL5) will handle `undefined` but its required to set the `slug` to empty string (`''`) on the `src/content/docs/index.md` file (`slug: ''`).
2. Inspect `Root Index` in dev console under `Issue #18` (there is no hyperlink generated)

Expected Result:
Link generated is `/index` and navigation successful
  - **NOTE:** - The generated link should be `/index` since its the root index in the collection/site.  Placing a value of `slug: ''` in the frontmatter for `src/content/docs/index.md` should result in the page being available at `/` (site root).

Actual Result:
Linked generated is `''` and no `href` in anchor tag (`<a>Root Index</a>`)

3. Go back to site root
4. Click on `Root Custom Slug` under `Issue #18`

Expected Result:
Link generated is `/custom-slug` and navigation successful

Actual Result: 
Link generated is `/customslugmd/custom-slug` and 404

5. Go back to site root
6. Click on `Guides Custom Slug` under `Issue #18`

Expected Result:
Link generated is `/guides/example-custom-slug` and navigation successful

Actual Result:
Link generated is `/guides/guides/example-custom-slug` and 404

### Additional Information
The requirement to have `contentPath` configured on the plugin to match the `docs` collection that Starlight uses (or anything else out there that uses a subfolder of `content` as the effective site root), makes it such that any other content collections are going to have issues with this plugin since there is only one `contentPath` currently from the plugins perspective.  This is something that should likely get added to the [README](https://github.com/vernak2539/astro-rehype-relative-markdown-links/blob/main/README.md) and possible consideration for future feature to offer a `filter` option so that the plugin could be added multiple times or an object/array that contains mappings.  Something to consider but not for today :)

### PR DESCRIPTION
**Pull request by techfg**
Resolves #18 

I based this PR off of PR #17 as it made solutioning for the issues covered in this one more straightforward to resolve than the prior code base would have.  With that said, the solution I came up with does introduce a new option [collectionPathMode](https://github.com/techfg/astro-rehype-relative-markdown-links/commit/86fb9ddafacfa8371fcb824851f7a05c05edc8d6#diff-619cc2239a7eb4ef05041767e6ab0e4fb069e98ee9d2c83c2d8e1865c475e141R26).  

Upon reviewing the potential approaches for addressing the issues, I just could not see a way to reliably and with certainty determine the collection path from the information we have available within the plugin.  The prior code and even PR #17 and this PR still assume that a content collection is a subdirectory of the content path - normal behavior in Astro - but not always the case as #18 describes.

Given that, the only way to know for certain if the `content collection` and `content path` are the same is for the consumer of the library to tell us 😦 

The default behavior (`ContentPathMode = 'subdirectory') still applies and works identical to the way it did prior to this PR where we assume the content collections are immediate child directories of the content path.  This PR simply allows for them to be the same on an opt-in basis.  The same notes/warnings apply from those mentioned in `Additional Information` in the OP of #18.

### CODE REVIEW

**Comment by techfg** [comment]
No worries :)  I'll merge but we might not need this - see #27 for some thoughts and lemme know what you think.

**Comment by techfg** [comment]
Just pushed a merge but its not correct as I double up some tests - fixing now and will push again, sorry!

**Comment by techfg** [comment]
@vernak2539  - Ok, merge fixed, all set for you.  FYI, similar to prior commits, I did not format the files to minimize diff alignment issues so they could likely use one :)

**Comment by techfg** [comment]
> No worries :) I'll merge but we might not need this - see #27 for some thoughts and lemme know what you think.

Also, lemme know your thoughts on this and to a lesser but related degree your thoughts on #26, as depending on what they are, we might not need this PR.

**Comment by vernak2539** [comment]
Interesting. I'll need a bit more time to parse and think about #26 and #27. 

But, that doesn't mean we can't merge this one first and go from there. Will review now

**Comment by techfg** [comment]
Yeah,  I'm still trying to think through all the scenarios across both issues lol 

I think 27 has merit and might be a better path forward, more consistent with how Astro handles things internally.  Still want to think it through some more.

For 26, I think we are going to run in to issues if we try to cross collection boundaries but there are benefits if the physical file structure matches the page path structure identically. 

For this PR, even if we don't need `collectionPathMode` after deciding on 27, can always remove since we're pre-v1.


Look forward to your thoughts on 26 & 27 and lemme know if you have any questions on this PR in meantime. 

Thanks!

**Pull request merged**
