### PR TITLE
fix: resolves #14, #15 & #16

### LINKED ISSUE #14: bug: Transformed url does not respect custom slug
When a page contains a custom slug, the transformed url is not respecting it and instead, generating the `astro default` slug via `githug-slugger`.

For example, in a file `/posts/post-3.md`:

```markdown
---
title: Post 3
slug: post.3
---

[Post 3](./post-3.md)
```

Should result in `/posts/post.3` but instead results in `/posts/post3`.

It appears in #9 logic was added to handle special characters, etc. which makes sense and was needed.  However, if a custom slug exists, it should use it. 

Astro [appears to handle this](https://github.com/withastro/astro/blob/ecb44351e98cfba575447699689b0ace49cd3c9d/packages/astro/src/content/utils.ts#L473) by generating the default slug but then checking for a custom slug and if exists, using it, else falling back on default.

Repro:
- <https://stackblitz.com/edit/withastro-astro-7ge5gz>

With Proposed Fixes from PR #21:
- <https://stackblitz.com/edit/withastro-astro-mtqt5k>

Steps to repro:
1. Open repro
2. Click on `Post 1` link
3. Click on either link under `Repro for Issue #14`

Expected Result:
Link should navigate to `/posts/post.3` or `/posts/archive.md/archive-1` (depending on link chosen)

Actual Result:
The `.` is stripped and results in 404

Additional Info:
You can see all links that Astro generates on home page under `Issue #14` heading

### LINKED ISSUE #15: bug: Content collection path segment is slugified
When a url is transformed, the content collection path segment is being slugified resulting in incorrect path being generated.

For example, in a content collection of `/posts.md`, in a file `post-3.md`, the resulting url will be `/postsmd/post-3` when it should be `/posts.md/post-3.

Astro [does not appear to slugify](https://github.com/withastro/astro/blob/ecb44351e98cfba575447699689b0ace49cd3c9d/packages/astro/src/content/utils.ts#L238) the content collection segment itself, only the path relative to it.

Repro:
- <https://stackblitz.com/edit/withastro-astro-7ge5gz>

With Proposed Fixes from PR #21:
- <https://stackblitz.com/edit/withastro-astro-mtqt5k>

Steps to repro:

1. Open repro
2. Click on `Post MD 1`
3. Click on either link under `Repro for Issue #15`

Expected Result:
Link should navigate to `/posts.md/post-md-1` or `/posts.md/post.md.2` (has a custom slug) depending on which link you clicked.

Actual Result:
`/posts.md` is sluggified to `/postsmd` resulting in 404

Additional Info:
You can see all links that Astro generates on home page under `Issue #15` heading

### LINKED ISSUE #16: bug: Incorrectly strips `index` from content collection root index page
When a content collection has an page in the root (e.g., `/collection/index.md`), the slug should remain `index` unless there is a custom slug defined.  For subdirectories (e.g., `/collection/subdir/index.md`), index should be stripped.

Found [this issue](https://github.com/withastro/astro/issues/7038) and confirmed behavior that Astro itself does not strip `index` for root pages in a collection unless custom slug is defined.

Repro: <https://stackblitz.com/edit/withastro-astro-7ge5gz?file=src%2Fpages%2Findex.astro>

Steps to reproduce:

1. Open repro
2. Click on `Post 1` link
3. Click on `Go to Other Stuff Index` under `Repro for Issue #16`

Expected Behavior:
Link should navigate to `/otherstuff/index`

Actual Behavior:
`index` is stripped and link results in 404

Additional Info:
1) Clicking on `Go to Other Stuff Subdir Index` works as `index` is properly stripped
2) Clicking on `Go to Posts Index` works as it has a custom slug
3) You can see all links that Astro generates on home page under Issue #16

### PR DESCRIPTION
**Pull request by techfg**
1. Fixed tests that were validating incorrect behavior (e.g., `index` in root should remain the slug)
2. Eliminated duplicate parsing of url segments & querystringparams
3. Added test coverage for various scenarios
4. Resolves #14, Resolves #15, Resolves #16

If it's agreeable to you that this PR and #13 should be merged, would recommend merging this one first as it #13 contains more isolated changes compared to main.

Open to any/all feedback!

# Potential Breaking Change
In PR #3 (based on issue #2), special case handling of `index` files was added.  The fix in this PR related to #16, while I believe it to be correct based on [this issue](https://github.com/withastro/astro/issues/7038), will be a breaking change for anyone taking advantage of the current method of stripping for root collection index files only (subdirs in the collection will still be stripped as they are in Astro).  Anyone needing a root collection index file to have `index` stripped from URL should apply a custom slug of empty string (`''`) as Astro requires.

### CODE REVIEW

**Comment by vernak2539** [comment]
@techfg do you have a link to this?

>Anyone needing a root collection index file to have index stripped from URL should apply a custom slug of empty string ('') as Astro requires.

**Comment by techfg** [comment]
> @techfg do you have a link to this?
> 
> > Anyone needing a root collection index file to have index stripped from URL should apply a custom slug of empty string ('') as Astro requires.

@vernak2539 - Sure, it's [here](https://github.com/withastro/astro/issues/7038).  I referenced that link in #16 and in the potential breaking changes section of this PR as well since it's rather important :)

**Comment by techfg** [comment]
@vernak2539 - You can also see that Astro only strips `/index` per this [this line of code](https://github.com/withastro/astro/blob/0fec72b35cccf80b66a85664877ca9dcc94114aa/packages/astro/src/content/utils.ts#L229) so root `index` slug would always remain `index` unless overridden via a slug.

**Comment by techfg** [comment]
> > If it's agreeable to you that this PR and #13 should be merged, would recommend merging this one first as it #13 contains more isolated changes compared to main.
> 
> Sorry! I didn't see this yet and now there's conflicts.
> 
> As an aside, is there a way to separate out the fixes for each issue into their own PR? Or, do you think since all the functionality you're submitting fixes for relates to each other they should remain in a singular PR?

No worries!  Yeah, github had a heck of a time keeping the diff clean even though the changes themselves actually aren't that substantial.  

As for separating 14/15/16, they are all very closely aligned since they all directly relate to how the transform url gets generated.  The prior code did it in two different places (after #9 was added) so the first step was consolidating it back to one and then applying the logic for all three aspects.  I can separate if you prefer but it might be more busy work for both of us than its worth.  Completely up to you though, happy to go either way.  Also happy to merge main in to this PR to save you the trouble.

Lemme know what you prefer, any direction you choose works for me :)

**Comment by vernak2539** [comment]
Sounds good keeping them in the same PR! May just take me a bit more time to parse, but that's a me problem. 

Let me know once the conflicts are resolved, and I can have a look

**Comment by techfg** [comment]
@vernak2539 - `main` merged in to this PR.  Fortunately, the actual changes in `index.mjs` are rather small so hopefully will be easy enough to parse :)  Lemme know if you have any questions!

**Review by vernak2539 — COMMENTED** [review]
Overall, this looks great! I've had a chance to play around with it, but going to take a bit more time to look at it a bit more. Hopefully that's okay. 

Would you mind adding comments to the changes in `src/index.mjs`? I think it would very much help me and others looking at this in the future

**Comment by vernak2539** [comment]
Also, after merging this, I'll be updating the async tests to be a different format, which may cause some conflicts in other PRs. Sorry, but I swear it will be better!

**Comment by techfg** [comment]
Hey @vernak2539 - 

I added some comments, let me know if this is what you had in mind or would like something different.  I'm glad you asked me to do this, found another bug (#25) while writing up the comments and also a potential feature (#24).

Re: `breaking change` - Agreed, don't think a major bump is needed given its stlil pre-release.  That said, would recommend adding info about this to the README & CHANGELOG for anyone currently using library and just informational for anyone in the future since it's likely to come up since it doesn't appear Astro has any official documentation on how this is handled internally.

Re: `tests` - Funny you should mention, I thought about refactoring while I was in there but avoided the temptation lol  A few things I considered but one was changing the way rehype is used to have a separate context for each test so they can run in parallel.  Unfortunately, it doesn't appear that node test runner has anything like [isolatemodulesasync](https://jestjs.io/docs/jest-object#jestisolatemodulesasyncfn) unless there is something your aware of (my first time using node test runner).  Would be ideal if you held off on this until after we finalize the remaining 3 PRs (the remaining 2 beyond this one are rather small and hopefully will be quick for you) but no worries if you want to do it now, happy to refactor to whatever approach you come up with!

**Comment by vernak2539** [comment]
>Unfortunately, it doesn't appear that node test runner has anything like [isolatemodulesasync](https://jestjs.io/docs/jest-object#jestisolatemodulesasyncfn) unless there is something your aware of (my first time using node test runner).

Yeah, my first time using it as well. They run really fast already, so didn't even think about getting them to run in parallel

>Would be ideal if you held off on this until after we finalize the remaining 3 PRs (the remaining 2 beyond this one are rather small and hopefully will be quick for you) 

No worries! I can hold off.

>Agreed, don't think a major bump is needed given its stlil pre-release. That said, would recommend adding info about this to the README & CHANGELOG

👍

**Comment by techfg** [comment]
@vernak2539 - 

Thanks for merging, awesome!  

re: `tests` - Not sure what IDE you use, but one thing I noticed in VSCode using the [node test runner extension](https://marketplace.visualstudio.com/items?itemName=connor4312.nodejs-testing) is that it doesn't detect the subtests.  It's really a bug in the extension since subtests are completely valid but just FYI as you look to refactor tests since I'm not sure what you are thinking :)  From what I could tell, you have the subtests in-place because of the lack of support for something similar to `isolatemoduleasync` since the tests can't run in parallel because of the way rehype uses the file history.  Appreciate you holding off until after we decide on the PRs that remain, looking forward to your improvements!

re: `readme` - I saw the update you made, however I don't think it's completely accurate.  The plugin still strips `/index` (a subdirectory index), it just doesn't strip `index` (root index) any more.  The change made in #3 was correct with regards to subdirectory stripping, just not root stripping so the regex is on `/index` instead of just `index`.  Recommend making that clear in the README if you think appropriate.

re: `changelog` - I saw the `Fixed` bullet under v.0.9.0 only cross-references #14, recommend including #15 & #16 if you think appropriate.

Thanks again!

**Comment by techfg** [comment]
re: `tests` - Yeah, I was just using the CLI, easy enough and was really fast which was impressive.  For the refactor, I actually tried to the same (similar) approach you linked to but ran in to issues with rehype as it was seeming to share its state across each test because they were running in parallel that way vs. serially in the prior approach, this is why I was looking in to a solution for something similar to `isolatedModuleAsync` so that each test would get its own `rehype` module and not share state.  Maybe I just structured them wrong - if your refactor works, awesome, much cleaner - just be careful and run the tests a lot to make sure there isn't any race/state conditions :)

re: `changelog` - Understood, only main downside to what's there now is that there is no way for a user to know that 14/15/16 were all fixed in v0.9.0 without looking at the PR directly (which most won't do 😦 ).  

re: `readme` - Couple of minor suggestions:


> In PR https://github.com/vernak2539/astro-rehype-relative-markdown-links/pull/3 (based on issue https://github.com/vernak2539/astro-rehype-relative-markdown-links/issues/2), special case handling of index files was added where the `index` would be stripped from the URL. For example, `src/content/collection/dir/index.md` would be transformed into `/collection/dir`. This functionality was applied to `index.md` files both at the content collection root and content collection subdirectories.
In [PR #17](https://github.com/vernak2539/astro-rehype-relative-markdown-links/pull/17), applying this functionality to `index.md` at the collection root was removed based on the way Astro handles content at site/collection root vs. subdirectories (see [this issue](https://github.com/withastro/astro/issues/7038)). If you want to have your collection root `index.md` be transformed without the `index` slug,  utilitize the [slug frontmatter option](https://docs.astro.build/en/guides/content-collections/#defining-custom-slugs) provided by Astro setting your slug to empty string (`''`).

**Comment by techfg** [comment]
Adding more clarity in last sentence:

> In [PR #17](https://github.com/vernak2539/astro-rehype-relative-markdown-links/pull/17), applying this functionality to `index.md` at the collection root was removed based on the way Astro handles content at site/collection root vs. subdirectories (see [this issue](https://github.com/withastro/astro/issues/7038)). If you want to have your collection root `index.md` be transformed without the `index` slug,  utilitize the [slug frontmatter option](https://docs.astro.build/en/guides/content-collections/#defining-custom-slugs) provided by Astro setting your slug to empty string (`''`) and ensure your `getStaticPaths()` returns `undefined` for the slug of the content collection root `index.md`.

**Comment by vernak2539** [comment]
Thanks for the content suggestions. README is updated!

**Comment by techfg** [comment]
@vernak2539  - 

So it was bugging me that when the changelog generated for v0.9.0, it included the fix for 14 but not 15 & 16 which seemed odd since the commit message contained reference to all three of them as being resolved.

I looked in to autochangelog (pretty cool tool) and it seems that its logic looks for any referenced commits inside the commit message, however, it's [regex](https://github.com/cookpete/auto-changelog/blob/master/src/commits.js#L12C29-L12C153) looks for individual mentions of issues, not ones separated by commas, etc.  So, with the commit message I had `.... Resolves #14, #15 & #16....` it only picked up 14.  

Just FYI for future that whenever multiple issues are addressed in a single commit, ensure that they are fully qualified as resolved/closed/etc. (e.g., `Resolved #14, Resolved #15, Resolved #16 or separate lines ,etc.)

**Comment by vernak2539** [comment]
Thanks for this @techfg! I've ended up switching to https://github.com/github-changelog-generator/github-changelog-generator, which is much nicer and does all this stuff (even credit attribution... thought the other one did, but weirdly it didn't). so far, it's super nice. likely will try to do the stuff automatically on merge of tags

**Comment by techfg** [comment]
Changelog looks good!  Only downside is ruby is required so if anyone else needs to generate changelog, will take a few extra steps (e.g., install ruby, etc.) - possibly there is a way to automate that in a script or at least updating readme with information.  Not needed for now though!  In meantime, you can remove [changelog script](https://github.com/vernak2539/astro-rehype-relative-markdown-links/blob/main/package.json#L35) 😄

**Comment by vernak2539** [comment]
>Only downside is ruby is required so if anyone else needs to generate changelog, will take a few extra steps (e.g., install ruby, etc.)

Yeah true, but it's a free github action due to it being public code! #winning

>Not needed for now though! In meantime, you can remove [changelog script](https://github.com/vernak2539/astro-rehype-relative-markdown-links/blob/main/package.json#L35) 😄

Updated in #41! Good catch, thank you!

**Pull request merged**
